CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY, name TEXT NOT NULL, industry TEXT, location TEXT, website TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS competitors (id INTEGER PRIMARY KEY, customer_id INTEGER, name TEXT NOT NULL, website TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE TABLE IF NOT EXISTS sources (id INTEGER PRIMARY KEY, competitor_id INTEGER NOT NULL, url TEXT NOT NULL, kind TEXT NOT NULL, access_method TEXT NOT NULL DEFAULT 'web', allowed_by_robots INTEGER NOT NULL, status TEXT NOT NULL, last_checked TEXT, last_hash TEXT, FOREIGN KEY(competitor_id) REFERENCES competitors(id), UNIQUE(competitor_id,url));
CREATE TABLE IF NOT EXISTS observations (id INTEGER PRIMARY KEY, source_id INTEGER NOT NULL, observed_at TEXT NOT NULL, content_hash TEXT NOT NULL, title TEXT, text TEXT, metadata TEXT, FOREIGN KEY(source_id) REFERENCES sources(id));
CREATE TABLE IF NOT EXISTS changes (id INTEGER PRIMARY KEY, source_id INTEGER NOT NULL, detected_at TEXT NOT NULL, change_type TEXT NOT NULL, summary TEXT NOT NULL, old_hash TEXT, new_hash TEXT, evidence TEXT, severity INTEGER DEFAULT 1, FOREIGN KEY(source_id) REFERENCES sources(id));
CREATE TABLE IF NOT EXISTS findings (id INTEGER PRIMARY KEY, competitor_id INTEGER NOT NULL, created_at TEXT NOT NULL, category TEXT NOT NULL, claim TEXT NOT NULL, finding_type TEXT NOT NULL, confidence REAL NOT NULL, evidence TEXT NOT NULL, FOREIGN KEY(competitor_id) REFERENCES competitors(id));
CREATE TABLE IF NOT EXISTS reports (id INTEGER PRIMARY KEY, customer_id INTEGER, period_start TEXT NOT NULL, period_end TEXT NOT NULL, generated_at TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE TABLE IF NOT EXISTS alert_rules (id INTEGER PRIMARY KEY, customer_id INTEGER, rule_name TEXT NOT NULL, category TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE TABLE IF NOT EXISTS jobs (id INTEGER PRIMARY KEY, job_type TEXT NOT NULL, target_id INTEGER, scheduled_for TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT);
